# Generated by Django 3.1.5 on 2021-01-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_uoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uom',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uom',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uom',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uom',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
