# Generated by Django 3.1.5 on 2021-01-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210123_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uoms',
            field=models.ManyToManyField(to='store.UOM'),
        ),
    ]
