# Generated by Django 3.1.5 on 2021-01-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210123_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uoms',
        ),
        migrations.AddField(
            model_name='product',
            name='uoms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.uom'),
        ),
    ]
