# Generated by Django 3.1.5 on 2021-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210123_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uoms',
        ),
        migrations.AddField(
            model_name='product',
            name='uoms',
            field=models.ManyToManyField(to='store.UOM'),
        ),
    ]
